name: Build and Test

on:
  push:
    branches:
      - next
  pull_request:

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    
    - name: Interactive build
      uses: ./.github/actions/build

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
