name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - next
  pull_request:

jobs:
  init:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

  build:
    needs: init
    uses: ./.github/workflows/incremental_build.yaml
    with:
      configuration: 'Release'
      force_restore: false
    secrets: inherit
