name: Build and Test

on:
  push:
    branches:
      - next
  pull_request:

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout, Cache, and Build
      uses: ./.github/actions/build

    - name: Run tests
      run: dotnet test --no-build --verbosity normal
