name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - next
      - main

jobs:
  build:
    uses: ./.github/workflows/incremental_build.yaml
    with:
      configuration: 'Release'
      force_restore: false
    secrets: inherit
