name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/incremental_build.yaml
    with:
      configuration: 'Release'
      force_restore: false
    secrets: inherit
  
  init:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
  release:
    runs-on: windows-latest
    needs: [build, init]
    
    steps:
    
    - name: Download a Build Artifact
      id: download
      uses: actions/download-artifact@v3
    
    - name: Create GitHub Release and upload artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: ${{steps.download.outputs.download-path}}
